--- 
title: "Wait Time at Walt Disney World"
author: "Mildred Ouyang, Xiaoyang Song, Liwen Zhu* (Group 12)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
<script src="https://d3js.org/d3.v7.js"></script>

# Introduction
Disneyland is one of the most popular themed parks in the world. However, visitors often long wait in lines for each attraction. They may spend hours waiting and enjoy the attraction for less than five minutes. There is no need to mention possible bad weather; waiting in line when it rains or the temperature is below 32 or above 100 Fahrenheit is uncomfortable. The visitors could only enjoy a few attractions in a day while wasting most of their precious time waiting. We all have experienced long waiting for attractions in Disneyland, so we would like to find a way to minimize the waiting time as much as possible. What's more, Covid-19 has dramatically impacted the world, including Disneyland. Many people choose to stay at home instead of having fun outside. Also, Disneyland was closed on March 16, 2020. We will show how the covid influence the waiting time. In this project, We will explore Disney Magic Kingdom Park’s historical wait time and discover some patterns. Our findings suggest the waiting time does vary before and after covid began. It is not distributed uniformly yearly, monthly, and daily. There are some times tourists spend less time waiting. Furthermore, we conclude some strategies which help us spend time wisely and enjoy as many attractions as possible.  
