# Results
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="zoom.js"></script>

## Waiting Time Pattern Analysis

```{r}
process_name <- function(csv) {
    return(gsub("  ", "", gsub(".csv", "", gsub("_", " ", csv))))
}

get_attraction_name <- function() {
    return(lapply(list.files("Data/data/Magic Kingdom/xysong_python"), process_name)) # nolint
}
# get_attraction_name() #nolint


read_all <- function() {
    library(hash)
    filenames <- list.files("Data/data/Magic Kingdom/xysong_python") # nolint
    dict <- hash()
    for (csv in filenames) {
        dict[[process_name(csv)]] <- read.csv(sprintf("Data/data/Magic Kingdom/xysong_python/%s", csv)) # nolint
    }
    return(dict)
}
```
```{r}
library(ggplot2)
library(ggeasy)
library(dplyr)
library(lubridate)
library(tidyverse)
# source("Utility/utils.R")

all_dsets <- read_all()
dumbo <- all_dsets[["dumbo"]]
class(dumbo)
# Elementary statistics
head(dumbo)
# Get all datasets
df_all <- bind_rows(lapply(get_attraction_name(), function(i) all_dsets[[i]]))
# nrow(df_all)

# Example
# head(dsets)
group_by <- function(df) {
    # Process dataframe
    dsets <- df %>%
        dplyr::mutate(Datetime = as.Date(Datetime, "%Y-%m-%d %H:%M:%S")) %>%
        dplyr::mutate(month = lubridate::floor_date(Datetime, "month")) %>%
        dplyr::group_by(month) %>%
        dplyr::summarise(avg = sum(Waiting.Time) / n())
    return(dsets)
}

plot_time_series <- function(dsets, name) { # Plot
    g <- ggplot(dsets, aes(month, avg), type = "l") +
        geom_line(color = "black") +
        scale_x_date(date_labels = "%b %Y", date_breaks = "6 months", guide = guide_axis(angle = 45)) + # nolint
        xlab("Month") +
        ylab("Average Waiting Time (minutes)") +
        ggtitle(sprintf("%s: Average Waiting Time (By Month)", name)) +
        ggeasy::easy_center_title()
    return(g)
}
identify_abnormal <- function(g, start, end, text_y) {
    g <- g + annotate("rect", xmin = start, xmax = end, ymin = -Inf, ymax = Inf, fill = "lightblue", alpha = 0.5) # nolint
    # Append text
    g <- g + annotate("text", x = end + 10, y = text_y * (2 / 3), label = "Covid \nDisruption", color = "green", hjust = 0) # nolint
    return(g)
}

plot_in_one_shot <- function(df, name) {
    grouped_dsets <- group_by(df)
    g <- plot_time_series(grouped_dsets, name)
    start <- as.Date("2020-01-01")
    end <- as.Date("2020-12-01")
    g <- identify_abnormal(g, start, end, max(grouped_dsets$avg))
    return(g)
}
# nrow(df_all)
plot_in_one_shot(df_all, "All Attractions")
```

:::{#abnormal_plot}
```{r, fig.show="hold", out.width="20%"}
all_plot <- list()
names <- get_attraction_name()
length(names)
# names
# names[[1]]
for (i in 1:25) {
    name <- names[[i]]
    all_plot[[i]] <- plot_in_one_shot(all_dsets[[name]], name)
}
for (g in all_plot){
  print(g)
}
```
:::


### Identify cyclical patterns

:::{#facet}
```{r, fig.show="hold", out.width="50%"}
dumbo <- all_dsets[["dumbo"]]
# dumbo
head(dumbo)
# sum(dumbo$Waiting.Time) / nrow(dumbo)
group_by_date <- function(df) {
    # Process dataframe
    dsets <- df %>%
        dplyr::mutate(Datetime = as.Date(Datetime, "%Y-%m-%d %H:%M:%S")) %>%
        dplyr::group_by(Datetime) %>%
        dplyr::summarise(avg = sum(Waiting.Time) / n()) %>%
        dplyr::mutate(yr = year(Datetime))
    return(dsets)
}
dset <- group_by_date(dumbo)
head(dset)
g <- ggplot(dset, aes(as.Date(format(Datetime, format = "%m-%d"), "%m-%d"), avg)) + # nolint
    geom_line(color = "grey30") +
    geom_point(size = 0.1) +
    scale_x_date(date_labels = "%b", date_breaks = "1 months", guide = guide_axis(angle = 45)) + # nolint
    facet_grid(yr ~ ., scale = "free_y") +
    geom_smooth(se = FALSE)
g
print(head(dset, 100), n = 100)
as.character(as.Date("2020/01/01"))
# grid.arrange(g,g, ncol=2)
g
g
g
head(dset, 100)
```
:::




